// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Total number of exported functions:   4

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    second_contract
    (
        init => init
        acceptKdaPayment => accept_kda_payment
        rejectKdaPayment => reject_kda_payment
        getkdaTokenName => get_contract_kda_token_identifier
    )
}
