// Code generated by the klever-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Total number of exported functions:   7

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    kda_system_sc_mock
    (
        init => init
        issue => issue_fungible
        issueNonFungible => issue_non_fungible
        issueSemiFungible => issue_semi_fungible
        registerMetaKDA => issue_meta_kda
        setSpecialRole => set_special_roles
        registerAndSetAllRoles => register_and_set_all_roles
    )
}
