[package]
name = "second-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.second-contract]
path = ".."

[dependencies.klever-sc]
version = "0.44.0"
path = "../../../../../../framework/base"

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../../../framework/meta"
default-features = false
