[package]
name = "vec-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vec-repeat]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../../framework/meta"
