[package]
name = "erc1155-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.erc1155]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../../framework/meta"
default-features = false
