// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           26
// Total number of exported functions:  27

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    use_module
    (
        init => constructor_in_a_module
        checkFeatureGuard => check_feature_guard
        checkPause => check_pause
        call_contract_base_full_path_endpoint => call_contract_base_full_path_endpoint
        call_contract_base_endpoint => call_contract_base_endpoint
        call_mod_a => call_mod_a
        call_mod_b => call_mod_b
        call_mod_c => call_mod_c
        only_owner_mod_endpoint => only_owner_mod_endpoint
        call_derived_not_owner_only => call_derived_not_owner_only
        only_admin_mod_endpoint => only_admin_mod_endpoint
        call_derived_not_admin_only => call_derived_not_admin_only
        countTo100 => count_to_100
        dnsRegister => dns_register
        issueToken => issue_token
        setFeatureFlag => set_feature_flag_endpoint
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        stake => stake
        unstake => unstake
        voteSlashMember => vote_slash_member
        slashMember => slash_member
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}
