[package]
name = "nft-minter-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.nft-minter]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
