// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Total number of exported functions:   4

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler_with_message!();

klever_sc_wasm_adapter::endpoints! {
    panic_message_features
    (
        init => init
        panicWithMessage => panic_with_message
        panicAfterLog => panic_after_log
        sc_panic => sc_panic
    )
}
