[package]
name = "abi-tester-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.abi-tester]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
default-features = false
