[package]
name = "kda-system-sc-mock-meta"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.kda-system-sc-mock]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
