// Code generated by the klever-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    digital_cash
    (
        init => init
        fund => fund
        withdraw => withdraw
        claim => claim
        claim_fees => claim_fees
        deposit_fees => deposit_fees
        forward => forward
        amount => get_amount
        deposit => deposit
    )
}
