// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    digital_cash
    (
        init => init
        whitelistFeeToken => whitelist_fee_token
        blacklistFeeToken => blacklist_fee_token
        claimFees => claim_fees
        getAmount => get_amount
        payFeeAndFundKDA => pay_fee_and_fund_kda
        payFeeAndFundKLV => pay_fee_and_fund_klv
        fund => fund
        depositFees => deposit_fees
        withdraw => withdraw
        claim => claim
        forward => forward
        deposit => deposit
    )
}
