[package]
name = "composability-tests"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dev-dependencies.builtin-func-features]
path = "builtin-func-features"

[dev-dependencies.proxy-test-first]
path = "proxy-test-first"

[dev-dependencies.proxy-test-second]
path = "proxy-test-second"

[dev-dependencies.klever-sc-scenario]
version = "0.44.0"
path = "../../../framework/scenario"
