// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           25
// Total number of exported functions:  26

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    rust_testing_framework_tester
    (
        init => init
        sum => sum
        sum_sc_result => sum_sc_result
        get_caller_legacy => get_caller_legacy
        get_klv_balance => get_klv_balance
        get_kda_balance => get_kda_balance
        receive_klv => receive_klv
        recieve_klv_half => recieve_klv_half
        receive_kda => receive_kda
        reject_payment => reject_payment
        receive_kda_half => receive_kda_half
        receive_multi_kda => receive_multi_kda
        send_nft => send_nft
        mint_kda => mint_kda
        burn_kda => burn_kda
        get_block_epoch => get_block_epoch
        get_block_nonce => get_block_nonce
        get_block_timestamp => get_block_timestamp
        get_random_buffer_once => get_random_buffer_once
        get_random_buffer_twice => get_random_buffer_twice
        call_other_contract_execute_on_dest => call_other_contract_execute_on_dest
        call_other_contract_add_async_call => call_other_contract_add_async_call
        getTotalValue => get_total_value
        execute_on_dest_add_value => execute_on_dest_add_value
        addValue => add
        panic => panic
    )
}
