[package]
name = "use-module-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.use-module]
path = ".."

[dependencies.klever-sc]
version = "0.44.0"
path = "../../../../framework/base"

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
