[package]
name = "empty-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.empty]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
