// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    nft_storage_prepay
    (
        init => init
        setCostPerByte => set_cost_per_byte
        reserveFunds => reserve_funds
        claim => claim
        depositPaymentForStorage => deposit_payment_for_storage
        withdraw => withdraw
        getCostForSize => get_cost_for_size
        getDepositAmount => get_deposit_amount
        getCostPerByte => cost_per_byte
    )
}
