[package]
name = "digital-cash-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.digital-cash]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
