[package]
name = "proxy-recursive-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.proxy-recursive]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
