name = "dice"
contract_trait = "Dice"
src_file = "dice.rs"
rename_pairs = [
]
files_include = [
    "meta",
    "src",
    "common",
    "common/rand",
    "common/rand/src",
    "wasm/Cargo.toml",
    "Cargo.toml",
]
