// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    lottery_kda
    (
        init => init
        start => start
        createLotteryPool => create_lottery_pool
        buy_ticket => buy_ticket
        determine_winner => determine_winner
        status => status
        changeContractName => change_contract_name
        getLotteryInfo => lottery_info
        getLotteryWhitelist => lottery_whitelist
    )
}
