use crate::tx_execution::{
    builtin_function_names::KLEVER_CREATE_ASSET_FUNC_NAME, BlockchainVMRef,
};

use crate::tx_mock::{BlockchainUpdate, TxCache, TxInput, TxResult};

use super::super::builtin_func_trait::BuiltinFunction;

pub struct KleverCreateAsset;

impl BuiltinFunction for KleverCreateAsset {
    fn name(&self) -> &str {
        KLEVER_CREATE_ASSET_FUNC_NAME
    }

    fn execute<F>(
        &self,
        tx_input: TxInput,
        tx_cache: TxCache,
        _vm: &BlockchainVMRef,
        _f: F,
    ) -> (TxResult, BlockchainUpdate)
    where
        F: FnOnce(),
    {
        // Parse arguments
        // arg[0]: asset_type (u32)
        // arg[1]: name (ManagedBuffer)
        // arg[2]: ticker (ManagedBuffer)
        // arg[3]: precision (u32)
        // arg[4]: owner (ManagedAddress)
        // arg[5]: logo (ManagedBuffer)
        // arg[6]: initial_supply (BigUint)
        // arg[7]: max_supply (BigUint)
        // ... remaining args are properties, attributes, uris, royalties

        let ticker = tx_input.args[2].clone();
        let owner = tx_input.args[4].as_slice();
        
        // Create a simple token identifier from the ticker
        // In a real scenario, this would be generated by the system
        let token_identifier = ticker;

        // Initialize the token data for the caller
        tx_cache.with_account_mut(&tx_input.from, |account| {
            account.kda.set_roles(token_identifier.to_vec(), vec![]);
        });

        // If the owner is different from the caller, also initialize for owner
        if owner != tx_input.from.as_bytes() {
            let owner_address = crate::types::VMAddress::from_slice(owner);
            tx_cache.with_account_mut(&owner_address, |account| {
                account.kda.set_roles(token_identifier.to_vec(), vec![]);
            });
        }

        let tx_result = TxResult {
            result_status: 0,
            result_values: vec![token_identifier],
            ..Default::default()
        };

        (tx_result, tx_cache.into_blockchain_updates())
    }
}
