// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           16
// Total number of exported functions:  18

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    crypto_zombies
    (
        init => init
        upgrade => upgrade
        set_crypto_kitties_sc_address => set_crypto_kitties_sc_address
        generate_random_dna => generate_random_dna
        create_random_zombie => create_random_zombie
        is_ready => is_ready
        dna_digits => dna_digits
        zombies_count => zombies_count
        zombies => zombies
        zombie_owner => zombie_owner
        crypto_kitties_sc_address => crypto_kitties_sc_address
        cooldown_time => cooldown_time
        owned_zombies => owned_zombies
        level_up => level_up
        withdraw => withdraw
        change_name => change_name
        change_dna => change_dna
        attack => attack
    )
}
