// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    local_kda_and_nft
    (
        init => init
        issueFungibleToken => issue_fungible_token
        localMint => local_mint
        localBurn => local_burn
        nftIssue => nft_issue
        nftAddQuantity => nft_add_quantity
        nftBurn => nft_burn
        transfer_nft_and_execute => transfer_nft_and_execute
        setLocalRoles => set_local_roles
        getFungibleKdaBalance => get_fungible_kda_balance
        getNftBalance => get_nft_balance
        lastIssuedToken => last_issued_token
        lastErrorMessage => last_error_message
    )
}
