// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    crowdfunding_erc20
    (
        init => init
        fund => fund
        status => status
        claim => claim
        get_target => target
        get_deadline => deadline
        get_deposit => deposit
        get_erc20_contract_address => erc20_contract_address
        get_total_balance => total_balance
    )
}
