[package]
name = "deployer-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.deployer]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../../framework/meta"
default-features = false
