[package]
name = "rust-snippets-generator-test-meta"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.rust-snippets-generator-test]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
default-features = false
