[package]
name = "proxy-pause-wasm"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = [ "cdylib",]

[workspace]
members = [ ".",]

[dev-dependencies]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = false

[dependencies.proxy-pause]
path = ".."

[dependencies.klever-sc-wasm-adapter]
version = "0.43.3"
path = "../../../../framework/wasm-adapter"
