// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    erc721
    (
        init => init
        mint => mint
        approve => approve
        revoke => revoke
        transfer => transfer
        totalMinted => total_minted
        tokenOwner => token_owner
        tokenCount => token_count
        approval => approval
    )
}
