// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Total number of exported functions:   6

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    deployer
    (
        init => init
        upgrade => upgrade
        getDeployedContracts => deployed_contracts
        deploy => deploy
        deleteLast => delete_last
        upgradeDeployed => upgrade_deployed
    )
}
