
[package]
name = "dice-meta"
version = "0.0.0"
authors = ["Beroni Magalhaes <beroni@klever.io>"]
edition = "2021"
publish = false

[dependencies.dice]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
