// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Total number of exported functions:   4

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::external_view_init! {}

klever_sc_wasm_adapter::external_view_endpoints! {
    abi_tester
    (
        external_view => external_view
        payable_any_token => payable_any_token
        label_a => label_a
    )
}
