// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Total number of exported functions:  14

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    rewards_distribution
    (
        init => init
        depositRoyalties => deposit_royalties
        raffle => raffle
        claimRewards => claim_rewards
        computeClaimableAmount => compute_claimable_amount
        getRaffleId => raffle_id
        getCompletedRaffleIdCount => completed_raffle_id_count
        getRoyalties => royalties
        getNftRewardPercent => nft_reward_percent
        getWasClaimed => was_claimed
        getSeedNftMinterAddress => seed_nft_minter_address
        getBrackets => brackets
        getLastRaffleEpoch => last_raffle_epoch
        getNftTokenId => nft_token_id
    )
}
