[package]
name = "erc20-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.erc20]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../../framework/meta"
