// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    bonding_curve_contract
    (
        init => init
        sellToken => sell_token_endpoint
        buyToken => buy_token_endpoint
        deposit => deposit_endpoint
        setBondingCurve => set_bonding_curve_endpoint
        claim => claim_endpoint
        view_buy_price => view_buy_price
        view_sell_price => view_sell_price
        getTokenAvailability => get_token_availability
    )
}
