// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Total number of exported functions:   4

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::external_view_init! {}

klever_sc_wasm_adapter::external_view_endpoints! {
    multi_contract_features
    (
        external_pure => external_pure
        sample_value_external_get => sample_value_external_get
        sample_value_external_set => sample_value_external_set
    )
}
