// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Total number of exported functions:   7

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    crypto_bubbles
    (
        init => init
        topUp => top_up
        withdraw => withdraw
        joinGame => join_game
        rewardWinner => reward_winner
        rewardAndSendToWallet => reward_and_send_to_wallet
        balanceOf => player_balance
    )
}
