// Code generated by the klever-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    crowdfunding_kda
    (
        init => init
        fund => fund
        status => status
        getCurrentFunds => get_current_funds
        claim => claim
        getTarget => target
        getDeadline => deadline
        getDeposit => deposit
        getCrowdfundingTokenIdentifier => cf_token_identifier
    )
}
