name = "empty"
contract_trait = "EmptyContract"
src_file = "empty.rs"
rename_pairs = []
files_include = [
    "meta",
    "scenarios",
    "src",
    "tests",
    "Cargo.toml",
    "kleverkapp.json",
]
