[package]
name = "str-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.str-repeat]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
