[package]
name = "queue-repeat"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/queue_repeat.rs"

[dependencies.benchmark-common]
path = "../benchmark-common"


[dependencies.klever-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.klever-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
