[package]
name = "basic-features"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/basic_features_main.rs"

[dependencies.klever-sc]
version = "0.43.3"
path = "../../../framework/base"

[dev-dependencies.klever-sc-scenario]
version = "0.43.3"
path = "../../../framework/scenario"

[dependencies.klever-sc-modules]
version = "0.43.3"
path = "../../../contracts/modules"

[dev-dependencies.kda-system-sc-mock]
path = "../kda-system-sc-mock"
