// Code generated by the klever-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Total number of exported functions:   6

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    proxy_test_first
    (
        init => init
        deploySecondContract => deploy_second_contract
        upgradeSecondContract => upgrade_second_contract
        forwardToOtherContract => forward_to_other_contract
        forwardToOtherContractWithCallback => forward_to_other_contract_with_callback
        messageOtherContract => message_other_contract
    )
}
