// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Total number of exported functions:   3

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::external_view_init! {}

klever_sc_wasm_adapter::external_view_endpoints! {
    use_module
    (
        external_view_mod_a => external_view_mod_a
        external_view_mod_b => external_view_mod_b
    )
}
