// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Total number of exported functions:   5

#![no_std]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    proxy_test_second
    (
        init => init
        upgrade => upgrade
        payMe => pay_me
        payMeWithResult => pay_me_with_result_endpoint
        messageMe => message_me
    )
}
