// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Total number of exported functions:   5

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    parent
    (
        init => init
        deposit => deposit
        deployChildContract => deploy_child_contract
        executeOnDestIssueToken => execute_on_dest_issue_token
        getChildContractAddress => child_contract_address
    )
}
