// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Total number of exported functions:   9

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    seed_nft_minter
    (
        init => init
        claimAndDistribute => claim_and_distribute
        getMarketplaces => marketplaces
        getNftCount => nft_count
        getDistributionRules => distribution_rules
        issueToken => issue_token
        buyNft => buy_nft
        getNftPrice => get_nft_price
        getNftTokenId => nft_token_id
    )
}
