// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           44
// Total number of exported functions:  45

#![no_std]

klever_sc_wasm_adapter::allocator!();
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    kapps
    (
        init => init
        deposit_check => deposit_check
        transfer_kda => transfer_kda
        kda_create => kda_create
        kda_create_nft => kda_create_nft
        mint => mint
        burn => burn
        wipe => wipe
        pause => pause
        resume => resume
        change_owner => change_owner
        add_role => add_role
        remove_role => remove_role
        update_metadata => update_metadata
        stop_nft_mint => stop_nft_mint
        update_logo => update_logo
        change_royalties_receiver => change_royalties_receiver
        update_staking => update_staking
        update_fee_pool => update_fee_pool
        stop_royalties_change => stop_royalties_change
        stop_metadata_change => stop_metadata_change
        update_royalties => update_royalties
        update_uris => update_uris
        freeze => freeze
        unfreeze => unfreeze
        delegate => delegate
        undelegate => undelegate
        claim => claim
        withdraw => withdraw
        sell => sell
        buy => buy
        deposit => deposit
        vote => vote
        ito_config => ito_config
        ito_set_prices => ito_set_prices
        ito_update_status => ito_update_status
        ito_update_receiver_address => ito_update_receiver_address
        ito_update_max_amount => ito_update_max_amount
        ito_update_default_limit_per_address => ito_update_default_limit_per_address
        ito_update_times => ito_update_times
        ito_update_whitelist_status => ito_update_whitelist_status
        ito_add_to_whitelist => ito_add_to_whitelist
        ito_remove_from_whitelist => ito_remove_from_whitelist
        ito_update_whitelist_times => ito_update_whitelist_times
        set_account_name => set_account_name
    )
}
