name = "adder"
contract_trait = "Adder"
src_file = "adder.rs"
rename_pairs = []
files_include = [
    "meta",
    "scenarios",
    "src",
    "tests",
    "Cargo.toml",
    "README.md",
    "sc-config.toml",
    "kleverkapp.json",
]
