[package]
name = "deployer"
version = "0.0.0"
authors = ["Klever <contact@klever.io>"]
edition = "2021"
publish = false

[lib]
path = "src/deployer.rs"

[dependencies.klever-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.klever-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
