[package]
name = "adder-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.adder]
path = ".."

[dependencies.klever-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
default-features = false
