[package]
name = "alloc-features-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.alloc-features]
path = ".."

[dependencies.klever-sc-meta]
version = "0.44.0"
path = "../../../../framework/meta"
default-features = false
