name: Proxy compare - newly generated vs present in file tree

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  proxy_compare:
    name: Proxy compare - newly generated vs present in file tree
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup default 1.89.0
          rustup update
          rustup target add wasm32-unknown-unknown

      - name: Install prerequisites
        run: |
          cargo install --path framework/meta
          sc-meta install wasm32

      - name: Run proxy compare
        run: |
          cd contracts
          sc-meta all proxy --compare