name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  template_test_released:
    if: vars.TEST_TEMPLATE_RELEASED == 'true'
    name: Template tool test - released templates
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-A dead_code"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rust
        run: |
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Install external prerequisites
        run: |
          mkdir "$HOME/koperator"

          curl -o "$HOME/koperator/operator" ${{vars.KOPERATOR_URL}}
          chmod +x "$HOME/koperator/operator"

          curl -o "$HOME/koperator/libvmexeccapi.so" ${{vars.LIBVMEXECCAPI_URL}}

          export LD_LIBRARY_PATH="$HOME/koperator"
          export PATH="$HOME/koperator:$PATH"
          operator --version

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-
  
      - name: Cargo Target Cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-target-

      - name: Install prerequisites
        run: |
          cargo install wasm-opt
          cargo install --path framework/meta
          which wasm-opt

      - name: Create operator account
        run: |
          export LD_LIBRARY_PATH="$HOME/koperator"
          export PATH="$HOME/koperator:$PATH"

          cd "$HOME/koperator"
          operator account create

      - name: Run template tool test
        run: |
          export LD_LIBRARY_PATH="$HOME/koperator"
          export PATH="$HOME/koperator:$PATH"
          export OPERATOR_KEY_FILE="$HOME/koperator/walletKey.pem"

          cd framework/meta
          cargo test --features template-test-released --test template_test
