[package]
name = "erc721"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@multiversx.com>",]
edition = "2021"
publish = false

[lib]
path = "src/erc721.rs"


[dependencies.klever-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.klever-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
